"""cards table

Revision ID: 0303dbc7ddcd
Revises: d6619bed4542
Create Date: 2021-11-10 19:32:55.711184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0303dbc7ddcd'
down_revision = 'd6619bed4542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcgplayer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=120), nullable=True),
    sa.Column('mana_cost', sa.String(length=40), nullable=True),
    sa.Column('cmc', sa.Integer(), nullable=True),
    sa.Column('type_line', sa.String(length=40), nullable=True),
    sa.Column('oracle_text', sa.String(length=200), nullable=True),
    sa.Column('power', sa.String(length=2), nullable=True),
    sa.Column('toughness', sa.String(length=2), nullable=True),
    sa.Column('colors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('color_identity', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('reprint', sa.Boolean(), nullable=True),
    sa.Column('set', sa.String(length=3), nullable=True),
    sa.Column('set_name', sa.String(length=40), nullable=True),
    sa.Column('set_type', sa.String(length=10), nullable=True),
    sa.Column('collector_number', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(length=8), nullable=True),
    sa.Column('artist', sa.String(length=20), nullable=True),
    sa.Column('edhrec_rank', sa.Integer(), nullable=True),
    sa.Column('usd_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_name'), 'card', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_name'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
