"""add created_at column on Users

Revision ID: 5d905cf0581e
Revises: 0303dbc7ddcd
Create Date: 2021-11-10 20:08:53.484710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d905cf0581e'
down_revision = '0303dbc7ddcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_card_color_identity'), 'card', ['color_identity'], unique=False)
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_index(op.f('ix_card_color_identity'), table_name='card')
    # ### end Alembic commands ###
